### ISSUE TITLE
Non-Docker implementation

### ISSUE THREAD

**Issue by modem7** [webdes03/Fitbit-Telegraf#1]
Heya, 

I've managed to get everything working except the last couple of steps.
 
I suspect because I don't have docker and my telegraf instance is running as a locally running daemon, the conf + JSON file needs to be different. 

When I import the JSON, there are no variables listed, no data collector or database fields available. Are you able to share the dashboard on Grafana so I can try importing it that way?

Unsure where to proceed in this case! Are you able to assist?

Thanks!

**Comment by webdes03** [comment]
The only advice I can offer is to break it into two steps. Run the fitbit script by itself and confirm that it's actually running as intended before you get into executing it with telegraf. You'll have to set the correct path in the fitbit script, as well as build out the rest of the telegraf config. The example only covers the script input, not the output communication to influxdb.

**Comment by modem7** [comment]
Have moved onto other projects. Will close the issue unless someone else is interested in this functionality
